model:
  channels: 32
  num_blocks: 7
  semantic_classes: 8  #
  instance_classes: 8 #
  sem2ins_classes: [] #[0, 1]
  semantic_only: True
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
    class_numpoint_mean: [500, 500, 500, 500, 500, 500, 500,
                          500]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [] #[0, 1]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: False
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 1 #100
  fixed_modules: []

data:
  train:
    type: 's3dis'
    data_root: 'dataset/s3dis/preprocess'
    prefix: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
    suffix: '_inst_nostuff.pth'
    repeat: 20 #20 #1
    training: True
    voxel_cfg:
      scale: 350 #50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 125 #5000
  test:
    type: 's3dis'
    #data_root: 'dataset/s3dis/preprocess'
    data_root: 'dataset/s3dis/preprocess_sample'
    prefix: 'Area_1'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 350 # 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 125 # 5000

dataloader:
  train:
    batch_size: 4
    num_workers: 4 #4 #1
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.001 # 0.004

save_cfg:
  semantic: True
  offset: True
  instance: False

fp16: False
epochs: 50
step_epoch: 0
save_freq: 2
pretrain: ''  #'./hais_ckpt_spconv2.pth' /home/potato/workplace/SoftGroup/work_dirs/weights-scratch/epoch_77.pth
work_dir: ''
